### ISSUE TITLE
Ignore switch case default cases which can't be covered

### ISSUE THREAD

**Issue by Hollerweger** [jacoco/jacoco#1211]
### Scenario

* JaCoCo version: (from right bottom corner of JaCoCo report)
  * 0.8.6
* Operating system: 
  * Windows
* Tool integration: Maven / Ant / CLI / API 
  * Maven
* Description of your use case:

Java Switch default cased can't be convered if all other cases are covered:

```
switch (enum) {
	case CASE_1:
		mappedPolicy = mapAccessRulePolicy((AccessRulePolicy) policy);
				break;
	case CASE_2:
		mappedPolicy = mapPsaKeyPolicy((PSAKeyUsagePolicy) policy);
		break;
	default:
               //Throw Exception in case a new Enum value is added in future and not yet supported
               throw new UnsupportedOperationException("Not supported enum: " + enum.getName());
```

Jacoco should add an option to ignore/mark switch default cases as covered.

### Current Behaviour
Switch default cases are makred as uncovered in case all other cases are covered even if coverage is not possible.

### Wanted Behaviour
Jacoco should add an option to ignore/mark switch default cases as covered.
If possible Jacoco can check if all other cases are covered first, if not then a simple config option would be enough.

### Possible Workarounds
Add unwanted Enums like UNKOWN or DEFAULT and try to cover default case with them.

**Comment by Copainbig** [comment]
I can look at that, but are we sure we want to do this, since here ([PR-923](https://github.com/jacoco/jacoco/pull/923)), it was decided to not filter user code?

**Comment by mukuldhariwal94** [comment]
+1

**Comment by BobanNikolov** [comment]
+1

**Comment by jorisgeer** [comment]
Result is a falsely reported missed branch. I would classify it as a bug. JaCoco assumes an value outside the enum class has to be handled. But being outside the class definition, you cannot generate it.

**Comment by wrayphi** [comment]
It would be great if this could be filtered as it is impossible to cover via test and means that our coverage stats have false positives that we cannot address.
Also applies to the newer style switch for example:
`enum Example {
  ONE,
  TWO
}


class ImpossibleToCover {

  static String switchWithBranchThatCannotBeCovered(Example e) {
    return switch(e) {
      case ONE -> "one";
      case TWO -> "two";
    };
  }
}
`

**Comment by M4urici0GM** [comment]
Up

**Comment by ddatsh** [comment]
any progress?

**Comment by marchof** [comment]
@ ddatsh @M4urici0GM Please understand that all progress is documented here. Such only distract maintainers from the actual work. That's why we cleanup our issues from useless clutter.

**Comment by daniel-frak** [comment]
Just chiming in to add that this issue extends to [switch expressions](https://openjdk.org/jeps/361), making it impossible to have 100% code coverage if they are used, due to the implicit default value (which is unreachable).

**Comment by forresthopkinsa** [comment]
Related to #771 and fixed in #1472

**Comment by nioncode** [comment]
This is still broken for multi-line switch cases I think, see: https://github.com/jacoco/jacoco/pull/1472#issuecomment-2082242485

**Comment by duracotton** [comment]
For me using Jacoco 0.8.12 it's still showing a missed branch:
![image](https://github.com/jacoco/jacoco/assets/25416153/39e4e0c7-cb41-4b17-84a0-84954b20e958)

**Comment by byte-artisan** [comment]
Since the issue is still in under triage, I would like to point another impact. In case the project use coverage minimal limits, for presented Switch, with 4 branches, including default, it is not possible to set coverage limit over than 75%, which is a low limit.

**Comment by Hollerweger** [comment]
> Related to [#771](https://github.com/jacoco/jacoco/issues/771) and fixed in [#1472](https://github.com/jacoco/jacoco/pull/1472)

@forresthopkinsa Is this not yet released or was it wrongly stated that it should fix the issue?

**Comment by forresthopkinsa** [comment]
> Is this not yet released or was it wrongly stated that it should fix this issue?

There are two different issues being described here. The one that was fixed was exhaustive switches incorrectly reporting an uncovered default case. The one you're talking about is exhaustiveness _inference_ which Jacoco still does not do.
